{{- if and .Values.georchestra.webapps.geoserver.enable .Values.georchestra.webapps.geoserver.jetty_monitoring -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "georchestra.fullname" . }}-geoserver-pm
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    org.georchestra.service/name: georchestra-geoserver
spec:
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      org.georchestra.service/name: {{ include "georchestra.fullname" . }}-geoserver
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
  podMetricsEndpoints:
  - port: prometheus
{{- end }}
