{{- $webapp := .Values.georchestra.webapps.gateway -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-gateway-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gateway
{{- end }}