{{- if and .Values.georchestra.webapps.datafeeder.enable .Values.georchestra.webapps.datafeeder_frontend.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-import-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder-import
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-import
{{- end }}