{{- $webapp := .Values.georchestra.webapps.datafeeder_frontend -}}
{{- if and .Values.georchestra.webapps.datafeeder.enabled $webapp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-import-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder-import
  {{- with $webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-import
{{- end }}