{{- if and (.Values.database.geodata) (not .Values.database.geodata.auth.existingSecret ) }}
{{- $database := .Values.database -}}
{{- if not $database.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-database-georchestra-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ $database.auth.database | b64enc | quote }}
  {{- if $database.builtin }}
  host: {{ printf "%s-database" .Release.Name | b64enc | quote  }}
  {{- else }}
  host: {{ $database.auth.host | b64enc | quote }}
  {{- end }}
  password: {{ $database.auth.password | b64enc | quote }}
  port: {{ $database.auth.port | b64enc | quote }}
  user: {{ $database.auth.username | b64enc | quote }}
{{- end }}
{{- end }}
