{{- $rabbitmq := .Values.rabbitmq -}}
{{- $rabbitmq_storage := .Values.rabbitmq.storage -}}
{{- if and $rabbitmq.enabled $rabbitmq.storage (not $rabbitmq_storage.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-rabbitmq
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-rabbitmq
spec:
  accessModes:
  {{- if $rabbitmq_storage.accessModes }}
  {{- range $rabbitmq_storage.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- if (eq "-" $rabbitmq_storage.storage_class_name) }}
  storageClassName: ""
  {{- else if $rabbitmq_storage.storage_class_name }}
  storageClassName: {{ $rabbitmq_storage.storage_class_name }}
  {{- end }}
  {{- if $rabbitmq_storage.pv_name }}
  volumeName: {{ $rabbitmq_storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ $rabbitmq_storage.size }}
{{- end }}
