{{- if .Values.georchestra.webapps.extractorapp.enable -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-extractorapp-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-extractorapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-extractorapp
{{- end }}