{{- if .Values.georchestra.webapps.geoserver.enable -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-geoserver-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-geoserver
{{- end }}