{{- if .Values.georchestra.webapps.openldap.enable -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-openldap-data
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.georchestra.storage.storage_class_name }}
  storageClassName: {{ .Values.georchestra.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.georchestra.storage.openldap_data.pv_name }}
  volumeName: {{ .Values.georchestra.storage.openldap_data.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.openldap_data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-openldap-config
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.georchestra.storage.storage_class_name }}
  storageClassName: {{ .Values.georchestra.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.georchestra.storage.openldap_config.pv_name }}
  volumeName: {{ .Values.georchestra.storage.openldap_config.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.openldap_config.size }}
{{- end }}
