{{- $agent := .Values.datadirsync.agent -}}
{{- $fullname := include "datadirsync.fullname" . -}}
{{- if $agent.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-datadirsync-cm
data:
  rollout_mapping_config.yaml: |
{{- range $key, $values := $agent.rolloutDeploymentsMapping }}
    "{{ $key }}":
{{- range $values }}
      - {{ $fullname }}-{{ . }}
{{- end }}
{{- end }}
{{- end }}
